[batch]
size        = 500
max_wait    = 10
buffer_size = 100000

[cache]
enabled     = false
directory   = "/tmp/cache"
batch_size  = 500
wait        = 100

[write]
timeout     = 20
threads     = 1000
repeat      = 3
delay_time  = 3
streams     = [
  { listen=":6086", location = ["http://127.0.0.1:8086"] }
]

[monit]
listen      = ":5000"

[limits]

  [limits.host]
  Enabled   = true
  Regexp    = ".*host=(.*?)[\\s,$].*"
  Replace   = "$1"
  Limit     = 0

  [limits.write]
  Enabled   = false
  Regexp    = ".*host=(.*?)[\\s,$].*"
  Replace   = "all"
  Limit     = 0