[batch]
size        = 500
max_wait    = 10
buffer_size = 100000

[cache]
enabled     = false
directory   = "/tmp/cache"
wait        = 60
batch_cnt   = 1000

[write]
timeout     = 20
threads     = 1000
repeat      = 3
delay_time  = 3
streams     = [
  { listen=":6086", location = ["http://127.0.0.1:8086"] }
]

[monit]
listen      = ":5000"

[limits]

  [limits.write]
  Enabled   = true
  Regexp    = "^[^,\\s\"=]+[,\\s].*$"
  Replace   = "all"
  Drop      = true

  [limits.host]
  Enabled   = false
  Regexp    = ".*host=(.*?)[\\s,$].*"
  Replace   = "$1"
  Drop      = false